package de.kai.arbeitszeitgeofence.domain
import de.kai.arbeitszeitgeofence.data.*
import java.time.*
import java.time.temporal.ChronoUnit
object WorkSessionManager {
 fun initialState() = ActiveStateEntity(isTracking=false, activeStartEpochMillis=null, isBreakRunning=false, breakStartEpochMillis=null, accumulatedBreakMinutes=0, insideGeofence=false, closedLocalDate=null)
 fun startWork(state: ActiveStateEntity, now: Instant, insideGeofence: Boolean): ActiveStateEntity = if (state.isTracking) state.copy(insideGeofence=insideGeofence) else state.copy(isTracking=true, activeStartEpochMillis=now.toEpochMilli(), isBreakRunning=false, breakStartEpochMillis=null, accumulatedBreakMinutes=0, insideGeofence=insideGeofence)
 fun startBreak(state: ActiveStateEntity, now: Instant): ActiveStateEntity = if (!state.isTracking || state.isBreakRunning) state else state.copy(isBreakRunning=true, breakStartEpochMillis=now.toEpochMilli())
 fun stopBreak(state: ActiveStateEntity, now: Instant): ActiveStateEntity { if (!state.isBreakRunning || state.breakStartEpochMillis == null) return state; val minutes = ChronoUnit.MINUTES.between(Instant.ofEpochMilli(state.breakStartEpochMillis), now).coerceAtLeast(0).toInt(); return state.copy(isBreakRunning=false, breakStartEpochMillis=null, accumulatedBreakMinutes=state.accumulatedBreakMinutes + minutes) }
 fun stopWork(state: ActiveStateEntity, now: Instant, localDate: LocalDate, source: TrackingSource, comment: String): Pair<ActiveStateEntity, WorkTimeEntryEntity?> { if (!state.isTracking || state.activeStartEpochMillis == null) return state.copy(insideGeofence=false) to null; val finalState = if (state.isBreakRunning) stopBreak(state, now) else state; val effectiveComment = if (finalState.accumulatedBreakMinutes == 0) listOf(comment, "Warnung: keine Pause erfasst").filter { it.isNotBlank() }.joinToString(" | ") else comment; val entry = WorkTimeEntryEntity(localDate=localDate.toString(), startEpochMillis=finalState.activeStartEpochMillis, endEpochMillis=now.toEpochMilli(), breakMinutes=finalState.accumulatedBreakMinutes, source=source.name, comment=effectiveComment, createdAtEpochMillis=now.toEpochMilli(), modifiedAtEpochMillis=now.toEpochMilli()); return finalState.copy(isTracking=false, activeStartEpochMillis=null, isBreakRunning=false, breakStartEpochMillis=null, accumulatedBreakMinutes=0, insideGeofence=false) to entry }
}
